// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF2y0_e4kpv_czEMIj3HE3tjrUY_YWQbU',
    appId: '1:954772503039:web:e8b4dcdcba1ebfed42cfca',
    messagingSenderId: '954772503039',
    projectId: 'crypto-wallet-a8f3d',
    authDomain: 'crypto-wallet-a8f3d.firebaseapp.com',
    databaseURL: 'https://crypto-wallet-a8f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-wallet-a8f3d.appspot.com',
    measurementId: 'G-ENFSLW9Z01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHV0ZL0WCkG8XfOgRS6SCe1gD1tpEt8h0',
    appId: '1:954772503039:android:535e1ce8c324ea5542cfca',
    messagingSenderId: '954772503039',
    projectId: 'crypto-wallet-a8f3d',
    databaseURL: 'https://crypto-wallet-a8f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-wallet-a8f3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAethC_UbqQJG6n93Qk-yp4pJE5uDjBllI',
    appId: '1:954772503039:ios:0108b2fb61ee0b6342cfca',
    messagingSenderId: '954772503039',
    projectId: 'crypto-wallet-a8f3d',
    databaseURL: 'https://crypto-wallet-a8f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-wallet-a8f3d.appspot.com',
    iosClientId: '954772503039-bf2l7qr7o01jvl39iav5c4c3t4vnlmuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.crypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAethC_UbqQJG6n93Qk-yp4pJE5uDjBllI',
    appId: '1:954772503039:ios:0108b2fb61ee0b6342cfca',
    messagingSenderId: '954772503039',
    projectId: 'crypto-wallet-a8f3d',
    databaseURL: 'https://crypto-wallet-a8f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-wallet-a8f3d.appspot.com',
    iosClientId: '954772503039-bf2l7qr7o01jvl39iav5c4c3t4vnlmuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.crypto',
  );
}
